### ISSUE TITLE
Support large images

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/tiny-skia#15]
Currently we're limited by 8191x8191. We have to port `SkDrawTiler`.

**Comment by jeffreyrosenbluth** [comment]
Any idea when this will be done. I'm really enjoying tiny-skia, but I want to make some very large images from printing.

**Comment by RazrFalcon** [comment]
No idea.

**Comment by jeffreyrosenbluth** [comment]
I'm thinking of taking this on. Can you point me to a skia class that you ported that you think would help as a reference?

**Comment by RazrFalcon** [comment]
It's actually a pretty easy task. Port [SkDrawTiler](https://github.com/google/skia/blob/f326e4faef66d529904a7b53eb931fd576c82887/src/core/SkBitmapDevice.cpp#L43) and test it carefully. I just don't have much time at the moment.

Afaik, it's basically draw first region, move to the next one, clip, draw again, and again.

**Comment by jeffreyrosenbluth** [comment]
Thanks, I'll have a look

**Comment by jeffreyrosenbluth** [comment]
I've started porting `SkDrawTiler` and I'm not sure what some of the analogous tiny_skia types are to some of the C++ types. In particular `SkBitmapDevice`, `SkDraw`, `SkTLazy<SkPostTranslateMatrixProvider>`, `SkRasterClp` and `SkIPoint`. Are there rust / tiny-skia versions of all of these? 
```class SkDrawTiler {
    enum {
        // 8K is 1 too big, since 8K << supersample == 32768 which is too big for SkFixed
        kMaxDim = 8192 - 1
    };

    SkBitmapDevice* fDevice;
    SkPixmap        fRootPixmap;
    SkIRect         fSrcBounds;

    // Used for tiling and non-tiling
    SkDraw          fDraw;

    // fCurr... are only used if fNeedTiling
    SkTLazy<SkPostTranslateMatrixProvider> fTileMatrixProvider;
    SkRasterClip                           fTileRC;
    SkIPoint                               fOrigin;

    bool            fDone, fNeedsTiling;```

**Comment by RazrFalcon** [comment]
Nope. It's hard to explain actually... tiny-skia is a reimplementation of Skia, not a port. There are tons of changes. I guess I will take a look at it on the weekends. It would be way easier than trying to explain how the internals work.

**Comment by jeffreyrosenbluth** [comment]
@RazrFalcon Wondering if you have had any time to look at this. If not, can you possibly outline for me what needs to be done so I can give it a go.

**Comment by RazrFalcon** [comment]
Nope. I did tried to implement this, but looks like it would be a fairly complicated change. And I don't have any free time lately.
And since this part was heavily modified, you have to have a very good understanding of how Skia works to port it (esentually re-implement from scratch).

**Comment by RazrFalcon** [comment]
Done. It wasn't extremely complicated, but not trivial either.

If you still interested in this feature - please test it out.

**Comment by jeffreyrosenbluth** [comment]
Thanks I will.

**Comment by jeffreyrosenbluth** [comment]
Works perfectly for me!

**Comment by RazrFalcon** [comment]
Glad to hear!
