### ISSUE TITLE
Contributing and Skia

### ISSUE THREAD

**Issue by therealbnut** [linebender/tiny-skia#16]
Hey, I've been using `resvg` for a while, it's really great! Recently I've noticed that there's a lot of changes on the backend, and I'm hoping to help so it won't stop me being able to use it in future.

My issue started when updating the latest `resvg` (`v0.11`), which uses a version of `tiny-skia` which no longer exists (`0.1`). I want to be able to compose text onto the output produced by `resvg`, but I'd rather not save it to to a raster first (performance).

I think an ideal solution for me is that `tiny-skia` can be built with either Rust-native or Skia-lib versions (using a rust feature), you can probably also use these versions to ensure compatibility between Skia and your library for testing.

I _think_ the changes and development overhead wouldn't be huge from my page, it might even make compatibility testing easier. Although I wanted to talk to you before I started. Are you open to contributions? Do you have any suggestions or requirements if I attempt this?

**Comment by RazrFalcon** [comment]
>either Rust-native or Skia-lib versions

What does it mean? You want to link the C++ Skia somehow?

As for the `resvg` output, I do plan to add an ability to render on a user-provided surface, so you would be able to use you own rendering library for text.

**Comment by therealbnut** [comment]
> You want to link the C++ Skia 

Yeah, perhaps it wouldn’t provide building or linking, but could leverage Skia if it’s already built/linked by an existing library. Alternatively just use one of those for the C++ Skia component.

> As for the resvg output, I do plan to add an ability to render on a user-provided surface, so you would be able to use you own rendering library for text.

How do you mean a user provided surface? Like C++ Skia? Because that would be perfect.

**Comment by RazrFalcon** [comment]
Well, the first point is obviously out of scope. As for the second one, yes, in v0.3 I plan to allow using `Canvas` on top of any pixmap, not only our RGBA8 one. So you would be able to pass your pixmap + channels info to the resvg and it will render SVG on it and not on a new one, as it currently does.
