### ISSUE TITLE
Expose clipping mask

### ISSUE THREAD

**Issue by sandmor** [linebender/tiny-skia#18]
Would be possible to make the clipping mask public? So lower level operations other than just replace one with another would be possible to implement externally without comprise the simplicity that this library seeks to maintain

**Comment by RazrFalcon** [comment]
Yes, I will make it public soon.

As for save/restore - I still haven't decided.

**Comment by sandmor** [comment]
> Yes, I will make it public soon.

Thank you
> As for save/restore - I still haven't decided.

If you want to maintain simplicity that can be implemented by the project that want to use `tiny-skia`
