### ISSUE TITLE
[Question] Rendering tiny-skia to screen

### ISSUE THREAD

**Issue by nemosupremo** [linebender/tiny-skia#19]
Sorry if this question potentially clogs your issues; I'm looking to use tiny-skia (or any lightweight rendering engine) to render some images and other barebones graphics to a screen under Wayland. Seeing how tiny-skia doesn't support this directly, what makes the most sense is to export the underlying rgba canvas then rendering it with something like gfx-rs. Is this a good/performant idea? Thanks for any pointers.

**Comment by RazrFalcon** [comment]
Right now, the only option is to copy pixels from the `Pixmap` to you native canvas/buffer. But the next release would gain an ability to render on top of a user-proved canvas (with limitations).

But yes, the general idea is that you have to copy/convert pixels yourself.
