### ISSUE TITLE
Access to clip mask content

### ISSUE THREAD

**Issue by sandmor** [linebender/tiny-skia#21]
I need to combine two clip mask, to do this I only need to execute `map(|a, b| a | b)` on every byte that makes up the mask, would be possible to implement byte level access to `ClipMask` or another mechanism to achieve this?.
Notice that two mask that I'm trying to combine has equal dimensions so that operation is totally valid even for a flat byte array

**Comment by RazrFalcon** [comment]
It's not possible right now and your implementation is flawed, because you're forgetting about anti-aliasing.

To illustrate the problem, `ClipMask` implementation in Skia is like 5000 LOC, while in skia it's just 300. There are tons of work and I don't have much time right now.

**Comment by RazrFalcon** [comment]
#22

**Comment by sandmor** [comment]
Thank you.
Sorry for the duplicating I forget to look if there was another issue about this

**Comment by RazrFalcon** [comment]
Don't worry. I've just created it.
