### ISSUE TITLE
Add Rotate Transform

### ISSUE THREAD

**Issue by pretzelhammer** [linebender/tiny-skia#24]
I've been using `tiny-skia` to learn and create generative artwork over the past couple days and I've been really enjoying it, I think the library has a really nice API. One thing I'm missing right now is the ability to easily rotate paths. I'm aware `resvg` uses `tiny-skia` as its backend and supports all of the SVG 1.1 spec which includes rotate transforms so is it possible to produce a rotate transform using the existing API? Even so, I think it would be a nice addition to the current Transform API.

**Comment by RazrFalcon** [comment]
Yes, the API is very bare-bone and any suggestions are welcome.

As for rotate, this is how `resvg` does it:

```rust
    /// Constructs a new rotate transform.
    #[inline]
    pub fn new_rotate(angle: f64) -> Self {
        let v = angle.to_radians();
        let a =  v.cos();
        let b =  v.sin();
        let c = -b;
        let d =  a;
        Transform::new(a, b, c, d, 0.0, 0.0)
    }

    /// Constructs a new rotate transform at the specified position.
    #[inline]
    pub fn new_rotate_at(angle: f64, x: f64, y: f64) -> Self {
        let mut ts = Self::default();
        ts.translate(x, y);
        ts.rotate(angle);
        ts.translate(-x, -y);
        ts
    }
```

So you can use it for now and I will add it to tiny-skia soon.
