### ISSUE TITLE
Plan to implement HTML Canvas features?

### ISSUE THREAD

**Issue by Brooooooklyn** [linebender/tiny-skia#3]
Is there any plan to implement full features HTML Canvas API? Like https://github.com/servo/pathfinder/tree/master/canvas?(It has no CPU backend for now)
I want write a high performance `node-canvas` library using skia. Maybe `tiny-skia` is better for `rust-skia`(I created it, but it's too complicated for write nodejs binding).

**Comment by RazrFalcon** [comment]
No. But it can be implemented on top of tiny-skia. I plan to keep the API as simple as possible. And more importantly, completely stateless, unlike the Canvas API.
